---
- name: Revoke VPN access for a user
  hosts: localhost
  pre_tasks:
    - block:
        - name: Ensure all vars defined
          assert:
            that: "{{ item }} is defined"
            msg: "variable {{ item }} must be defined"
          with_items:
            - str

  tasks:
    - set_fact:
        search_string: "search_{{ str }}"
      run_once: yes

    - name: Search if file exists
      stat:
        path: /home/afif/ansible-vpn/txt/{{ search_string }}.txt
      register: presence

    - name: Fail when file is not found
      ansible.builtin.fail:
        msg: String not found
      when: not presence.exists

    - name: Set searched string content
      copy:
        dest: "/home/afif/string.txt"
        content: "{{ search_string }}"

    - name: Changing perm sh
      file: dest=/home/afif/ansible-vpn/sh/test.sh mode=a+x

    - name: Test
      ansible.builtin.command: "/home/afif/ansible-vpn/sh/test.sh"
